# -*- coding: utf-8 -*-
COMUNI_PD = [
    'Abano Terme',
    'Agna',
    'Albignasego',
    'Anguillara Veneta',
    'Arquà Petrarca',
    'Arre',
    'Arzergrande',
    'Bagnoli di Sopra',
    'Baone',
    'Barbona',
    'Battaglia Terme',
    'Boara Pisani',
    'Borgoricco',
    'Bovolenta',
    'Brugine',
    'Cadoneghe',
    'Campodarsego',
    'Campodoro',
    'Camposampiero',
    'Campo San Martino',
    'Candiana',
    'Carceri',
    'Carmignano di Brenta',
    'Cartura',
    'Casale di Scodosia',
    'Casalserugo',
    'Castelbaldo',
    'Cervarese Santa Croce',
    'Cinto Euganeo',
    'Cittadella',
    'Codevigo',
    'Conselve',
    'Correzzola',
    'Curtarolo',
    'Este',
    'Fontaniva',
    'Galliera Veneta',
    'Galzignano Terme',
    'Gazzo',
    'Grantorto',
    'Granze',
    'Legnaro',
    'Limena',
    'Loreggia',
    'Lozzo Atestino',
    'Maserà di Padova',
    'Masi',
    'Massanzago',
    'Megliadino San Vitale',
    'Merlara',
    'Mestrino',
    'Monselice',
    'Montagnana',
    'Montegrotto Terme',
    'Noventa Padovana',
    'Ospedaletto Euganeo',
    'Padova',
    'Pernumia',
    "Piacenza d'Adige",
    'Piazzola sul Brenta',
    'Piombino Dese',
    'Piove di Sacco',
    'Polverara',
    'Ponso',
    'Pontelongo',
    'Ponte San Nicolò',
    'Pozzonovo',
    'Rovolon',
    'Rubano',
    'Saccolongo',
    'San Giorgio delle Pertiche',
    'San Giorgio in Bosco',
    'San Martino di Lupari',
    'San Pietro in Gu',
    'San Pietro Viminario',
    'Santa Giustina in Colle',
    "Sant'Angelo di Piove di Sacco",
    "Sant'Elena",
    "Sant'Urbano",
    'Saonara',
    'Selvazzano Dentro',
    'Solesino',
    'Stanghella',
    'Teolo',
    'Terrassa Padovana',
    'Tombolo',
    'Torreglia',
    'Trebaseleghe',
    'Tribano',
    'Urbana',
    'Veggiano',
    'Vescovana',
    "Vighizzolo d'Este",
    'Vigodarzere',
    'Vigonza',
    'Villa del Conte',
    'Villa Estense',
    'Villafranca Padovana',
    'Villanova di Camposampiero',
    "Vo'",
    'Due Carrare',
    'Borgo Veneto',
]

